server:
  port: 8080
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG
jwt:
  claimKey:
    username: "username"
    authorities: "authorities"
  secret: "wfhg9hr-1jfpjf-p3j-=vgf0pvmo3k=2-3rj0-3j=gn[=3-g[mj"
  header: Authorization
  expiration: 604800
  tokenHead: "Bearer "
oos:
  accessKey: "c4582dec5d0809103126"
  secretKey: "47c783687d4c452c5d71b817b8c481915fb0094a"
  endPoint: "http://oos-bj2.ctyunapi.cn"
  bucketName: "tagx00"